#
# Basic application information. This contains all the defaults. Overrides can be specified in:
#
#  config_[ENV].yml
#
# Setting the development environment in
#

app:
  name: Rubybones-based app
  environment: default
  version: 0.0.0

##########################################################################################
# What features the application uses

features:
  db: true

##########################################################################################
# Various paths

paths:
  root: ./
  logs: ./logs
  config: ./config

##########################################################################################
# DB coordinates and credentials

db:
  # You can se the db configuration here (not secure), or set environment variables (more secure):
  #   DBCONF_NAME
  #   DBCONF_USERNAME
  #   DBCONF_PASSWORD
  #
  dbname: example
  username: username
  password: password
